#!/bin/bash
set -e

NAME=veso
DEFAULT_FILE=/etc/default/${NAME}

# Source Veso default configuration
if [[ -f $DEFAULT_FILE ]]; then
  . $DEFAULT_FILE
fi

# Data directories for program data (cache, db), configs, and logs
PROGRAMDATA=${Veso_DATA_DIRECTORY-/var/lib/$NAME}
CONFIGDATA=${Veso_CONFIG_DIRECTORY-/etc/$NAME}
LOGDATA=${Veso_LOG_DIRECTORY-/var/log/$NAME}
CACHEDATA=${Veso_CACHE_DIRECTORY-/var/cache/$NAME}

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [[ -d /run/systemd/system ]] ; then
  systemctl --system daemon-reload >/dev/null || true
fi

case "$1" in
  purge)
    echo PURGE | debconf-communicate $NAME > /dev/null 2>&1 || true

    if [[ -x "/etc/init.d/veso" ]] || [[ -e "/etc/init/veso.connf" ]]; then
      update-rc.d veso remove >/dev/null 2>&1 || true
    fi

    if [[ -x "/usr/bin/deb-systemd-helper" ]]; then
      deb-systemd-helper purge veso.service >/dev/null
      deb-systemd-helper unmask veso.service >/dev/null
    fi

    # Remove user and group
    userdel veso > /dev/null 2>&1 || true
    delgroup --quiet veso > /dev/null 2>&1 || true
    # Remove config dir
    if [[ -d $CONFIGDATA ]]; then
      rm -rf $CONFIGDATA
    fi
    # Remove log dir
    if [[ -d $LOGDATA ]]; then
      rm -rf $LOGDATA
    fi
    # Remove cache dir
    if [[ -d $CACHEDATA ]]; then
      rm -rf $CACHEDATA
    fi
    # Remove program data dir
    if [[ -d $PROGRAMDATA ]]; then
      rm -rf $PROGRAMDATA
    fi
    # Remove binary symlink
    [[ -f /usr/bin/veso ]] && rm /usr/bin/veso
    # Remove sudoers config
    [[ -f /etc/sudoers.d/veso-sudoers ]] && rm /etc/sudoers.d/veso-sudoers
    # Remove anything at the default locations; catches situations where the user moved the defaults
    [[ -e /etc/veso ]] && rm -rf /etc/veso
    [[ -e /var/log/veso ]] && rm -rf /var/log/veso
    [[ -e /var/cache/veso ]] && rm -rf /var/cache/veso
    [[ -e /var/lib/veso ]] && rm -rf /var/lib/veso
    ;;
  remove)
    if [[ -x "/usr/bin/deb-systemd-helper" ]]; then
      deb-systemd-helper mask veso.service >/dev/null
    fi
    ;;
  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
