#!/bin/bash
set -e

NAME=veso
DEFAULT_FILE=/etc/default/${NAME}

# Source Veso default configuration
if [[ -f $DEFAULT_FILE ]]; then
  . $DEFAULT_FILE
fi

# Data directories for program data (cache, db), configs, and logs
PROGRAMDATA=${Veso_DATA_DIRECTORY-/var/lib/$NAME}
CONFIGDATA=${Veso_CONFIG_DIRECTORY-/etc/$NAME}
LOGDATA=${Veso_LOG_DIRECTORY-/var/log/$NAME}
CACHEDATA=${Veso_CACHE_DIRECTORY-/var/cache/$NAME}

case "$1" in
  remove|upgrade|deconfigure)
    echo "Stopping Veso!"
    # try graceful termination;
    if [[ -d /run/systemd/system ]]; then
      deb-systemd-invoke stop ${NAME}.service > /dev/null 2>&1 || true
    elif [ -x "/etc/init.d/${NAME}" ] || [ -e "/etc/init/${NAME}.conf" ]; then
      invoke-rc.d ${NAME} stop > /dev/null 2>&1 || true
    fi
    # Ensure that it is shutdown
    PIDFILE=$(find /var/run/ -maxdepth 1 -mindepth 1 -name "veso*.pid" -print -quit)
    [[ -n "$PIDFILE" ]] && [[ -s "$PIDFILE" ]] && Veso_PID=$(cat ${PIDFILE})
    # if its running, let's stop it
    if [[ -n "$Veso_PID" ]]; then
      # if veso is still running, kill it
      if [[ -n "$(ps -p $Veso_PID -o pid=)" ]]; then
        CPIDS=$(pgrep -P $Veso_PID)
        sleep 2 && kill -KILL $CPIDS
        kill -TERM $CPIDS > /dev/null 2>&1
      fi
      sleep 1
      # if it's still running, show error
      if [[ -n "$(ps -p $Veso_PID -o pid=)" ]]; then
        echo "Could not successfully stop Veso, please do so before uninstalling."
        exit 1
      else
        [[ -f $PIDFILE ]] && rm $PIDFILE
      fi
    fi
    if [[ -f /usr/lib/veso/bin/MediaBrowser.Server.Mono.exe.so ]]; then
      rm /usr/lib/veso/bin/MediaBrowser.Server.Mono.exe.so
    fi
    ;;
  failed-upgrade)
    ;;
  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
