name: Sync release-10.8.z to Upstream

on:
  schedule:
    - cron:  '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: release-10.8.z

    - name: Pull upstream changes
      id: sync
      uses: dannymichel/Fork-Sync-With-Upstream-action
      with:
        upstream_repository: jellyfin/jellyfin
        upstream_branch: release-10.8.z
        target_branch: release-10.8.z
        #github_token: ${{ secrets.GITHUB_TOKEN }}
